/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PenjualanKomputer;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayor Kucing
 */
public class Karyawan extends javax.swing.JFrame {
    
    private void kosong_form(){
        txtID.setText(null);
        txtNama.setText(null);
        buttonGroup1.clearSelection();
        cbAgama.setSelectedItem(null);
        txtAlamat.setText(null);
        txtHp.setText(null);
    }
    
    private void tampilkan_data(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("ID.");
        model.addColumn("Nama.");
        model.addColumn("Jenis Kelamin.");
        model.addColumn("Agama.");
        model.addColumn("Alamat.");
        model.addColumn("No Hp.");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM karyawan";
            Connection conn = (Connection)Config.configDB(); 
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{
                    no++,
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)
                });
                
            }
            tabelKaryawan.setModel(model);
            
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        setResizable(false);
        tampilkan_data();
        kosong_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtHp = new javax.swing.JTextField();
        cbAgama = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        tbGaji = new javax.swing.JButton();
        tbSimpan = new javax.swing.JButton();
        tbEdit = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        tbBatal = new javax.swing.JButton();
        tbKeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Laki = new javax.swing.JRadioButton();
        Perempuan = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Karyawan");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(700, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Karyawan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No HP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        txtID.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 113, -1));

        txtNama.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 162, -1));

        txtAlamat.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 217, -1));

        txtHp.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        getContentPane().add(txtHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 160, -1));

        cbAgama.setBackground(new java.awt.Color(102, 255, 153));
        cbAgama.setFont(new java.awt.Font("Levenim MT", 0, 12)); // NOI18N
        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Protestan", "Katolik", "Hindu", "Buddha", "Konghucu" }));
        cbAgama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cbAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 121, -1));

        tabelKaryawan.setBackground(new java.awt.Color(0, 153, 153));
        tabelKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 660, 150));

        tbGaji.setIcon(new javax.swing.ImageIcon("D:\\YOUTUBE ADSENSE\\Projectku\\Kuliah\\Tugas\\Kelas 2\\Pemrograman Berorientasi Objek\\Praktikum\\Project\\Data\\51455-pegawai-pnesdfsdfg-2.png")); // NOI18N
        tbGaji.setToolTipText("Gaji Karyawan");
        tbGaji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbGajiActionPerformed(evt);
            }
        });
        getContentPane().add(tbGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, 60));

        tbSimpan.setBackground(new java.awt.Color(51, 153, 0));
        tbSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tbSimpan.setText("Tambah");
        tbSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(tbSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        tbEdit.setBackground(new java.awt.Color(51, 153, 0));
        tbEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbEdit.setForeground(new java.awt.Color(255, 255, 255));
        tbEdit.setText("Edit");
        tbEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditActionPerformed(evt);
            }
        });
        getContentPane().add(tbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        tbHapus.setBackground(new java.awt.Color(204, 0, 0));
        tbHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbHapus.setForeground(new java.awt.Color(255, 255, 255));
        tbHapus.setText("Hapus Data");
        tbHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        tbBatal.setBackground(new java.awt.Color(51, 153, 0));
        tbBatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbBatal.setForeground(new java.awt.Color(255, 255, 255));
        tbBatal.setText("Clear");
        tbBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBatalActionPerformed(evt);
            }
        });
        getContentPane().add(tbBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        tbKeluar.setBackground(new java.awt.Color(204, 0, 0));
        tbKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbKeluar.setForeground(new java.awt.Color(255, 255, 255));
        tbKeluar.setText("Exit");
        tbKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(tbKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        buttonGroup1.add(Laki);
        Laki.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        Laki.setForeground(new java.awt.Color(255, 255, 255));
        Laki.setText("L");
        Laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LakiActionPerformed(evt);
            }
        });
        getContentPane().add(Laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        buttonGroup1.add(Perempuan);
        Perempuan.setFont(new java.awt.Font("Levenim MT", 1, 12)); // NOI18N
        Perempuan.setForeground(new java.awt.Color(255, 255, 255));
        Perempuan.setText("P");
        getContentPane().add(Perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\YOUTUBE ADSENSE\\Projectku\\Kuliah\\Tugas\\Kelas 2\\Pemrograman Berorientasi Objek\\Praktikum\\Project\\Data\\menuhasil.png")); // NOI18N
        jButton1.setToolTipText("Menu");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA KARYAWAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(90, 200, 200));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar?", "PERINGATAN", JOptionPane.YES_NO_OPTION);
        if(exit==JOptionPane.YES_OPTION){
            System.exit(0);
        }else{
            
        }
    }//GEN-LAST:event_tbKeluarActionPerformed

    private void tbGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbGajiActionPerformed
        // TODO add your handling code here:
        new Gaji_karyawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_tbGajiActionPerformed

    private void tbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSimpanActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = (Connection)Config.configDB();
            String sql = "INSERT INTO karyawan VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstm = conn.prepareStatement(sql);
            
            pstm.setString(1, txtID.getText());
            pstm.setString(2, txtNama.getText());
            
            String Jkel;
            if(Laki.isSelected()){
                Jkel = Laki.getText();
            }else{
                Jkel = Perempuan.getText();
            }
            pstm.setString(3, Jkel);
            
            String Agama;
            Agama = cbAgama.getSelectedItem().toString();
            pstm.setString(4, Agama);
            pstm.setString(5, txtAlamat.getText());
            pstm.setString(6, txtHp.getText());
            pstm.execute();
            
            
            JOptionPane.showMessageDialog(null, "Proses Simpan Berhasil!", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
            tampilkan_data();
            kosong_form();
                    
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbSimpanActionPerformed

    private void tabelKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKaryawanMouseClicked
        // TODO add your handling code here:
        int baris = tabelKaryawan.rowAtPoint(evt.getPoint());
        String ID = tabelKaryawan.getValueAt(baris, 1).toString();
        txtID.setText(ID);
        
        String Nama = tabelKaryawan.getValueAt(baris, 2).toString();
        txtNama.setText(Nama);
        
        String Jkel = tabelKaryawan.getValueAt(baris, 3).toString();
        if(Jkel.equals("L")){
            Laki.setSelected(true);
        }else{
            Perempuan.setSelected(true);
        }
        
        String Agama = tabelKaryawan.getValueAt(baris, 4).toString();
        cbAgama.setSelectedItem(Agama);
        
        String Alamat = tabelKaryawan.getValueAt(baris, 5).toString();
        txtAlamat.setText(Alamat);
        
        String NoHp = tabelKaryawan.getValueAt(baris, 6).toString();
        txtHp.setText(NoHp);
        
    }//GEN-LAST:event_tabelKaryawanMouseClicked

    private void tbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = (Connection)Config.configDB();
            String sql = "UPDATE karyawan SET id_karyawan=?, nama=?, jkel=?, agama=?, alamat=?, hp=? WHERE id_karyawan=?";
            PreparedStatement pstm = conn.prepareStatement(sql);
            
            
            pstm.setString(1, txtID.getText());
            pstm.setString(2, txtNama.getText());
            
            String Jkel;
            if(Laki.isSelected()){
                Jkel = Laki.getText();
            }else{
                Jkel = Perempuan.getText();
            }
            pstm.setString(3, Jkel);
            
            String Agama;
            Agama = cbAgama.getSelectedItem().toString();
            pstm.setString(4, Agama);
            
            pstm.setString(5, txtAlamat.getText());
            pstm.setString(6, txtHp.getText());
            pstm.setString(7, txtID.getText());
            pstm.execute();
            
            
            JOptionPane.showMessageDialog(null, "Edit Berhasil!", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        tampilkan_data();
        kosong_form();
    }//GEN-LAST:event_tbEditActionPerformed

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM karyawan WHERE id_karyawan='"+txtID.getText()+"'";
            Connection conn = (Connection)Config.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            
            
            JOptionPane.showMessageDialog(null, "Hapus Berhasil!", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        tampilkan_data();
        kosong_form();  
    }//GEN-LAST:event_tbHapusActionPerformed

    private void tbBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBatalActionPerformed
        // TODO add your handling code here:
        kosong_form();
    }//GEN-LAST:event_tbBatalActionPerformed

    private void LakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LakiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Laki;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKaryawan;
    private javax.swing.JButton tbBatal;
    private javax.swing.JButton tbEdit;
    private javax.swing.JButton tbGaji;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JButton tbSimpan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtHp;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
